import 'package:get/get_navigation/src/root/internacionalization.dart';

class Langauges extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'farmer_home': 'Farmer Home',
          'total_donations': 'Total Donations',
          "total_count": "Total Count",
          "wallet_balance": "Wallet Balance",
          'view_all_offers': "View All Offers",
          "approved_list": "Approved List",
          "farmer_profile": "Farmer Profile",
          "name": "Name",
          "email": "Email",
          "available_offer": "Available Offer",
          "phone": "Phone",
          "role": "Role",
          "location": "Location",
          "live_sensor_data": "Live Sensor Data",
          "total_plant_tree": "Total Plant Tree",
          "plant_a_tree": "Brikshya",
          "total_donated_amount": "Total Donated Amount",
          "recent_donations": "Recent Donations",
          "donate_money": "Plan Tree",
          "donor_profile": "Donor Profile",
          "edit_profile": "Edit Profile",
          "your_donation_giving_new_life": "Your Donation Giving New Life..",
          "pay_amount": "Pay Amount",
          "no_offer_available_right_now": "No offer available right now",
          "email_hint": "Enter your email",
          "password_hint": "Enter your password",
          "username": "Enter your username",
          "confirm_password": "Confirm your password",
          "view_all": "View All",
          "humidity": "Humidity",
          "view_detail": "View Detail",
          "edit_status": "Edit Status",
          "edit_detail": "Edit Detail",
          "temperature": "Temperature",
          "soil_temperature": "Soil Temperature",
        },
        'ne_NP': {
          'farmer_home': 'किसान घर',
          'total_donations': 'कुल दान',
          "available_offer": "उपलब्ध पेशकश",
          "total_count": "कुल गणना",
          "view_detail": "विस्तृत हेर्नुहोस्",
          'edit_status': "स्थिति सम्पादन गर्नुहोस्",
          "edit_detail": "सम्पादन गर्नुहोस्",
          "edit_profile": "प्रोफाइल सम्पादन गर्नुहोस्",
          "wallet_balance": "बटुआ संतुलन",
          'view_all_offers': "सबै पेशकश हेर्नुहोस्",
          "approved_list": "मान्यता प्राप्त सूची",
          "farmer_profile": "किसान प्रोफाइल",
          "name": "नाम",
          "email": "इमेल",
          "phone": "फोन",
          "role": "भूमिका",
          "humidity": "नमिलोता",
          "temperature": "तापमान",
          "soil_temperature": "माटो तापमान",
          "view_all": "सबै हेर्नुहोस्",
          "location": "स्थान",
          "live_sensor_data": "हेर्नुहोस् सेन्सर डाटा",
          "total_plant_tree": "कुल योजना रूख",
          "plant_a_tree": "वृक्ष",
          "total_donated_amount": "कुल दाता रकम",
          "recent_donations": "हालका दानहरू",
          "donate_money": "रुख लगाउनुहोस्",
          "donor_profile": "दाता प्रोफाइल",
          "your_donation_giving_new_life": "तपाईंको दानले नयाँ जीवन दिँदैछ",
          "pay_amount": "रकम भुक्तान गर्नुहोस्",
          "no_offer_available_right_now": "अहिले सम्म कुनै पेशकश उपलब्ध छैन",
        },
      };
}
